server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/eventms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
